spring.application.name=miproyecto

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/37e0e180-7aaa-44da-a299-59580e0362c2/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=7ed4e22b-555e-4d9a-9444-382dc49ebbd1